### ISSUE TITLE
result file is missing

### ISSUE THREAD

**Issue by ghost** [subho406/TF-Speech-Recognition-Challenge-Solution#2]
I download the code and database and it is work fine, but I can`t see any result directory to find the output in <notebook_name>.log.

can you explain exactly where I can find this directory or see the output?

![untitled](https://user-images.githubusercontent.com/44061158/46807557-09fc2580-cd1f-11e8-93c8-cbfffde46db6.png)

thank you

**Comment by ghost** [comment]
and how to change the labels of data? if I will test my database?

**Comment by subho406** [comment]
create a "results" folder in the project root directory. The python script you are running is a helper script that is supposed to run the training notebooks stored in the "notebook" directory.

**Comment by hussain199** [comment]
Is there any other folder should I create?

**Comment by hussain199** [comment]
And what if I want to change the database, what else I should change?

**Comment by ghost** [comment]
I have created result folder in path "C:\Users\Hussain\Anaconda3\results" and executed the code, the folder still empty.

**Comment by subho406** [comment]
I clearly mentioned project root directory, you have created one in anaconda for some reason. Please use a Linux distribution for running the code. And please read the requirements before opening an issue.

**Comment by ghost** [comment]
I traced it on windows. I didn`t know that it required Linux distribution. I`ll try it with Linux.
