### ISSUE TITLE
Error when i launch 1/2/3 options

### ISSUE THREAD

**Issue by Symfomany** [subho406/TF-Speech-Recognition-Challenge-Solution#9]
Enter option: 2
Executing notebook 01 Init.ipynb
[NbConvertApp] WARNING | pattern '../notebooks\\01\\' matched no files
[NbConvertApp] WARNING | pattern 'Init.ipynb' matched no files
  File "<stdin>", line 1
    This application is used to convert notebook files (*.ipynb) to various other
                   ^
SyntaxError: invalid syntax
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='1252'>
BrokenPipeError: [Errno 32] Broken pipe

**Comment by subho406** [comment]
Hi, the error indicates the notebook you want to execute cannot be found in the specified directory. Make sure you navigate to the scripts directory before running the execute_notebook.py script. Or you can avoid using the script and use jupyter notebook to run all cells.
